### ISSUE TITLE
Markbot issue

### ISSUE THREAD

**Issue by lexyfh** [lexyfh/using-svg-icons#1]
<img width="1792" alt="Screen Shot 2022-02-18 at 3 59 09 PM" src="https://user-images.githubusercontent.com/84150431/154760425-e5283400-1240-4b44-bc95-c863b5a95d0d.png">
Not sure why this isn't working
@wendywarren
@karenmendozagarza

**Comment by KarenMendozaGarza** [comment]
Hey Lexy, 
Your css isnt linked properly from your index, so your code isnt being applied. 
Here is a reminder on how to link the css: https://learn-the-web.algonquindesign.ca/topics/using-css/
I'm at a bit of a loss why your svg isn't applying any colour. The inspector says it should be inheriting. Maybe @wendywarren can weigh in on what might be missing.

**Comment by wendywarren** [comment]
Hi @lexyfh @KarenMendozaGarza,

I just opened the svg file with all three icons within Atom to check what the fill color is. Looks as though you didn't set the fill color to #000 in Illustrator before you exported. The icons have to either have no fill or exact black in order for you to apply another color within the css.

![Screen Shot 2022-02-23 at 2 43 48 PM](https://user-images.githubusercontent.com/12865609/155396455-16be67ad-cc9a-4789-8643-372119abbf0f.png)

Easiest fix is to open the dino-icons.svg and remove all 5 instances of `fill="#231f20"`. You would cmd f and remove.

Proper fix for next exercise would be to export with the fill changed to #000000 in Illustrator. :)

Let me know if you have any questions.

Wendy
